"""Generate N candidates with varied parameters → pick the majority vote.

Used for high-stakes queries to reduce variance in the reasoning pipeline.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from finroot.schemas.recommendation import Recommendation
from finroot.schemas.state import AgentState


class ConsistencyResult(BaseModel):
    """Result of a self-consistency check across multiple candidates.

    Attributes:
        candidates: The N generated candidates.
        winner: The majority-vote winner.
        agreement_score: Fraction of candidates matching the winner (0.0-1.0).
        dissenting_view: Note when agreement is below threshold.
    """

    candidates: list[Recommendation] = Field(..., min_length=1)
    winner: Recommendation
    agreement_score: float = Field(..., ge=0.0, le=1.0)
    dissenting_view: str | None = None


class SelfConsistency:
    """Generate N candidates with varied parameters → pick the majority vote.

    In mock mode (the default for this codebase), candidates are generated by
    deterministic rewording of the base candidate from state.
    """

    N_CANDIDATES: int = 3
    CONSENSUS_THRESHOLD: float = 0.7

    def check(self, state: AgentState) -> ConsistencyResult:
        """Generate N candidates from state and return the consensus result."""
        candidates = self._generate_candidates(state)
        return self.compute_consensus(candidates)

    def compute_consensus(
        self, candidates: list[Recommendation]
    ) -> ConsistencyResult:
        """Compare N candidates and return the majority vote.

        The winner is the candidate whose summary text appears most frequently.

        Args:
            candidates: List of Recommendation candidates to compare.

        Returns:
            ConsistencyResult with winner, agreement_score, dissenting_view.
        """
        groups: dict[str, list[Recommendation]] = {}
        for c in candidates:
            groups.setdefault(c.summary, []).append(c)

        winner_group = max(groups.values(), key=len)
        winner = winner_group[0]

        max_count = len(winner_group)
        if max_count == 1 and len(candidates) > 1:
            agreement_score = 0.0
        else:
            agreement_score = round(max_count / len(candidates), 2)

        dissenting_view: str | None = None
        if agreement_score < self.CONSENSUS_THRESHOLD:
            dissenting_view = "Low consensus — verify independently"

        return ConsistencyResult(
            candidates=candidates,
            winner=winner,
            agreement_score=agreement_score,
            dissenting_view=dissenting_view,
        )

    def _generate_candidates(
        self, state: AgentState
    ) -> list[Recommendation]:
        """Generate N candidates in mock mode (deterministic rewording).

        Args:
            state: The current AgentState with a base candidate.

        Returns:
            list[Recommendation]: N reworded variants.

        Raises:
            ValueError: If state has no candidate.
        """
        if state.candidate is None:
            raise ValueError(
                "Cannot generate consistency candidates: "
                "state.candidate is None. "
                "A base candidate is required."
            )
        base = state.candidate
        return [self._reword(base, i) for i in range(self.N_CANDIDATES)]

    @staticmethod
    def _reword(
        candidate: Recommendation, variant: int
    ) -> Recommendation:
        """Deterministic rewording for mock mode.

        Produces variants by prefixing the summary with different phrases.
        """
        prefixes = [
            "",
            "Consider: ",
            "Looking at this differently: ",
        ]
        prefix = prefixes[variant % len(prefixes)]
        return Recommendation(
            summary=prefix + candidate.summary,
            analysis=candidate.analysis,
            risks=list(candidate.risks),
            actions=list(candidate.actions),
            alternatives=list(candidate.alternatives),
            confidence=candidate.confidence,
            citations=list(candidate.citations),
            assumptions=list(candidate.assumptions),
            invalidation_conditions=list(candidate.invalidation_conditions),
        )


__all__ = ["ConsistencyResult", "SelfConsistency"]
